dao:
  service:
    connection-url: https://${dao.project}.api.test-athumi.eu
    frontend-base-url: https://${dao.project}.test-athumi.eu/demo
  gemeentes:
    security-method: client_secret
    token-uri: https://${dao.project}.api.test-athumi.eu/oauth2/token
