dao:
  service:
    connection-url: https://dao.api.test-athumi.eu
    frontend-base-url: https://dao.test-athumi.eu/demo
  gemeentes:
    security-method: client_credentials
    token-uri: https://dao.api.test-athumi.eu/oauth2/token
