dao:
  service:
    connection-url: https://elys.api.test-athumi.eu
    frontend-base-url: https://elys.test-athumi.eu/demo
  gemeentes:
    security-method: client_secret
    token-uri: https://elys.api.test-athumi.eu/oauth2/token
