spring:
  application:
    name: demo
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 19MB
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
    constructor-detector: use_properties_based
    time-zone: Europe/Brussels
    deserialization:
      adjust-dates-to-context-time-zone: true
    serialization:
      write-dates-with-context-time-zone: true

logging:
  config: classpath:logging/logback-spring.xml

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  tracing:
    enabled: false

server:
  port: 8082
  servlet:
    session:
      cookie:
        name: DEMO_SESSIONID
dao:
  project: ${PROJECT_NAME:elys}
  service:
    connection-url: http://localhost:8090
    frontend-base-url: http://localhost:8082
    frontend-url: http://localhost:8080
  gemeentes:
    security-method: client_secret
    token-uri: https://elys.api.test-athumi.eu/oauth2/token
    project-name: ${dao.project}
