dao:
  service:
    connection-url: https://${dao.project}.api.test-athumi.eu
    frontend-url: https://${dao.project}.test-athumi.eu
    frontend-base-url: ${dao.service.frontend-url}/demo
  gemeentes:
    security-method: client_secret
    token-uri: https://${dao.project}.api.test-athumi.eu/oauth2/token
