spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            token-uri: http://dao.api.test-athumi.eu/oauth2/token
dao:
  service:
    connection-url: http://dao.api.test-athumi.eu