spring:
  application:
    name: demo
  security:
    oauth2:
      registration:
        name: demo
      client:
        registration:
          demo:
            provider: spring
            client-authentication-method: client_secret_basic
            client-id: demo-client
            client-secret: demo-super-secret
            authorization-grant-type: client_credentials
            scope:
              - dao_lbbs
        provider:
          spring:
            token-uri: http://localhost:8090/oauth2/token
server:
  port: 8082
dao:
  service:
    connection-url: http://localhost:8090
logging:
  level:
    org:
      springframework:
        web: TRACE
        security: TRACE
