spring:
  application:
    name: demo
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 19MB

server:
  port: 8082
  servlet:
    session:
      cookie:
        name: DEMO_SESSIONID
dao:
  service:
    connection-url: http://localhost:8090
    frontend-base-url: http://localhost:8082
  gemeentes:
    security-method: client_secret
    token-uri: https://elys.api.test-athumi.eu/oauth2/token
  project: ${PROJECT_NAME:"dao"}