dao:
  service:
    connection-url: http://localhost:8090
    frontend-base-url: http://localhost:8082
  gemeentes:
    security-method: client_secret
    token-uri: http://localhost:8090/oauth2/token
    config:
      leuven:
        naam: Leuven
        kbonummer: '0207521503'
      oostende:
        naam: Oostende
        kbonummer: '0207436775'