spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            token-uri: https://dao.api.test-athumi.eu/oauth2/token
dao:
  service:
    connection-url: https://dao.api.test-athumi.eu