dao:
  service:
    connection-url: http://localhost:8090
    frontend-base-url: http://localhost:8082
  gemeentes:
    security-method: client_secret
    token-uri: https://dao.api.test-athumi.eu/oauth2/token
    config:
      leuven:
        naam: Leuven
        kbonummer: '0207521503'
        clientid: demo-client
        clientsecret: demo-client-leuven-secret
      oostende:
        naam: Oostende
        kbonummer: '0207436775'
        clientid: demo-client-oostende
        clientsecret: demo-client-oostende-secret