spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            token-uri: http://dao-backend-service:8080/oauth2/token
dao:
  service:
    connection-url: http://dao-backend-service:8080