package eu.athumi.dao.demoburgerlijkestand.adapter.dao.json.inlichtingenfiche;

public enum AsWettelijkePartnerType {
    NIET_VAN_TOEPASSING,
    SAMEN_MET_DE_DOODSKIST_BEGRAVEN,
    SAMEN_MET_DE_IN_EEN_LIJKWADE_GEHULDE_OVERLEDENE_BEGRAVEN,
    SAMEN_MET_DE_URNE_VAN_DE_OVERLEDENE_IN_EEN_URNENVELD_BEGRAVEN,
    SAMEN_MET_DE_URNE_VAN_DE_OVERLEDENE_IN_HET_COLUMBARIUM_GEPLAATST,
    SAMEN_MET_DE_AS_VAN_DE_OVERLEDENE_OP_EEN_STROOIWEIDE_UIT_TE_STROOIEN,
    SAMEN_MET_OVERLEDENE_IN_EEN_DOODSKIST_PLAATSEN_EN_BEGRAVEN,
}