package eu.athumi.dao.demoburgerlijkestand.adapter.dao.dto.type;

public enum BezwarenDTOType {
    BEZWAAR_TEGEN_CREMATIE,
    BEZWAAR_TEGEN_CONSERVERINGSTECHNIEKEN,
    BEZWAAR_TEGEN_VERVOER_ZONDER_KIST,
    BEZWAAR_TEGEN_SCHENKING_LICHAAM,
    GERECHTELIJK_GENEESKUNDIG_BEZWAAR_TEGEN_BEGRAFENIS_OF_CREMATIE;

}
