package eu.athumi.dao.demoburgerlijkestand.adapter.dao.json.historiek;

public enum GebeurtenisReden {
    //UITVAART_ONTKOPPELD
    UITVAART_ONTKOPPELD_DOOR_LOKAAL_BESTUUR,
    DOSSIER_GEANNULEERD_DOOR_UITVAART,

    //DOSSIER HEROPEND
    MANUEEL_HEROPEND,
    SOCIOECONOMISCHE_GEGEVENS_AANGEPAST,
    INLICHTINGENFICHE_AANGEPAST,
    HEROPEND_NA_BURGERAANVRAAG,
    TOESTEMMING_BEGRAFENIS_OF_CREMATIE_VERWIJDERD,

    LOKAAL_BESTUUR_VAN_BEHANDELING_GEWIJZIGD,
    MANUEEL_VERWIJDERD,
    MANUEEL_AFGESLOTEN,
    AFGESLOTEN_DOOR_BURGERAANVRAAG,
    AUTOMATISCH_AFGESLOTEN,
    OPGESTART_DOOR_UITVAART_ONDERNEMER;
}