package eu.athumi.dao.demoburgerlijkestand.adapter.dao.json.toestemming;

public enum ToestemmingVerwijderdDoor {
    LOKAAL_BESTUUR,
    INLICHTINGENFICHE,
    VERANTWOORDELIJKE_UITVAART_VERANDERD,
    VERANTWOORDELIJKE_GEMEENTE_VERANDERD,
    ANDERE_LAATSTE_WILSBESCHIKKING_VERWIJDERD,
    ANDERE_LAATSTE_WILSBESCHIKKING_GEREGISTREERD
}
